---

# project name
project_name: demo-flask-app

# home path for project and virtualenv, e.g. /home/ubuntu
home_path: /{{ user_name }}

# project path, e.g. /home/ubuntu/fvang
project_path: "{{ home_path }}/{{ project_name }}"

# flask app path, e.g. /home/ubuntu/fvang/fvang
application_path: "{{ project_path }}"